version: '2.2'
services:
    postgres:
        container_name: postgres
        image: al-postgres
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        restart: always
    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@alcolist.com"
            PGADMIN_DEFAULT_PASSWORD: "alcolist"
        ports:
            - "16543:80"
    al-backend:
        container_name: al-backend
        image: al-backend:latest
        ports: 
            - 8090:8090
        depends_on:
            - postgres
    al-frontend:
        container_name: al-frontend
        image: al-frontend:latest
        ports: 
            - 8080:8080
        depends_on:
            - al-backend